# Generated by Django 3.1.7 on 2021-03-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hentai_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hentai',
            options={'verbose_name': 'Hentai', 'verbose_name_plural': 'Hentai'},
        ),
    ]
