# Generated by Django 3.1.7 on 2021-05-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hentai_information', '0002_auto_20210508_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
