# Generated by Django 3.1.7 on 2021-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hentai_information', '0003_gamemodel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='level',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='nextGoal',
            field=models.IntegerField(default=15),
        ),
    ]
