# Generated by Django 3.1.7 on 2021-06-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hentai_information', '0005_auto_20210528_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boostdefault',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='autoClickPower',
            field=models.IntegerField(default=0),
        ),
    ]
